version: '3'

services:
  backup-service:
    build: .
    container_name: gdrive-sync
    restart: unless-stopped
    volumes:
      - ./test:/data
    env_file:
      - .env
    environment:
      - TZ=UTC
